---
grubconf: "{{ '/etc/grub.conf' if (ansible_distribution_major_version == '6' or ansible_distribution_major_version == '5' ) else '/etc/grub2.conf' }}"
fstab: /etc/fstab
mailconfig: /etc/exim/exim.conf
auditdconf: /etc/audit/auditd.conf
auditd_rules: /etc/audit/audit.rules
sshd_config: /etc/ssh/sshd_config

# set this to suit your domain and syslog server.
syslog_dest: "{{ '192.168.1.60' if ansible_domain == 'akait.local' else '192.168.2.60' }}"


ntp_server: "{{ 'a-p-ntp-01' if ansible_domain == 'akait.local' else 'a-o-ntp-01' if ansible_domain == 'akaitpp.local' else 'a-t-ntp-01'}}"
sudoers_file: "{{ '/etc/sudoers.d/10_qualys' if ansible_domain == 'akaittd.local' else '/etc/opt/quest/qpm4u/policy/sudoers'}}"
ftpd_package: 'vsftpd'
httpd_package: 'httpd'
# select yes to run the find commands in section9
verify_find: no
# set to yes if you want run the checks which uses scripts in files/bin
run_shell_scripts: no
banner_search_text: "Authorised users only"
log_files:
  - /var/log/messages
  - /var/log/secure
  - /var/log/maillog
  - /var/log/syslog
  - /var/log/kern.log
  - /var/log/cron
  - /var/log/spooler

# below settings are custom checks outside cis. this task is not enabled by default
# set this to suit your domain and puppet server, if you use puppet, if not, set puppet_check to no
puppet_server: "{{ 'puppet.akait.local' if ansible_domain == 'akait.local' else 'puppetpp.akaitpp.local' if ansible_domain == 'akaitpp.local' else 'akaittd.local'}}"
puppet_check: no
puppet_conf: /etc/puppetlabs/puppet/puppet.conf
# 
