- hosts: 
        - webservers 
#  become: true
  tasks:
        - name: "httpd daemon status"
          shell: "/usr/sbin/apachectl status | awk '/Active/ { print; exit } '"
          register: cmd_res
        - debug: msg={{ cmd_res.stdout }}
