- hosts: 
        - "{{ var_host }}" 
  become: true
  tasks:
        - name: "httpd daemon stop"
          shell: "/forms/apache24/bin/apachectl stop"
          register: cmd_res
        - debug: msg={{ cmd_res.stdout }}
