- hosts: 
        - webservers 
#  become: true
  tasks:
        - name: "httpd daemon status"
          shell: "/forms/apache24/bin/apachectl status | awk '/Server uptime/ { print; exit} '"
          register: cmd_res
        - debug: msg={{ cmd_res.stdout }}
