- hosts: 
        - webservers 
#  become: true
  tasks:
        - name: "httpd daemon status"
          shell: "/usr/sbin/apachectl status | awk '/Active/ { print; exit }'"
#          shell: "hostname"             
          register: cmd_res
        - set_fact:
             "{{ inventory_hostname }}={{ cmd_res.stdout }}"
        - debug: var={{ inventory_hostname }}
